services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "1935:1935"
      - "8888:8888"
      - "8554:8554"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
